#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 13 13:53:55 2025

@author: gamal
"""

## IMPORTS
import sys
import os
import datetime
import gpm # type: ignore
import numpy as np 
import pandas as pd 
import ximage  # noqa 
from matplotlib import pyplot as plt 
from gpm.io.local import get_local_filepaths # type: ignore

## Import local function
# PACKAGE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))
# OUTPUT_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", "data"))

from gpm_storm.gpm_storm.features.image import calculate_image_statistics